### ISSUE TITLE
Change the way to access MiniApp programs to make them more suitable for expanding platform interoperability

### ISSUE THREAD

**Issue by Ternence** [w3c/miniapp#126] opened 2020-09-10 13:20 UTC
It is difficult to solve the MiniApp AppKey distribution and query target Package URI by AppKey.
Can we build the de-centrally MiniApp platform system? 

Is it possible to use the domain name as the only AppKey of the MiniApp like the HTML5 web page? The browser can load a MiniApp program just like loading an HTML5 web page.

When a user accesses a MiniApp, the main part work for the vendor is that: 
- For the browser, request the manifest file in the origin server firstly. 
- Get the MiniApp Package URI and meta info from the Manifest.
- Fetch the package file and install it locally.
- Prepare render and logic worker and start the MiniApp pages.
- Update the local cache package file until over max-age.

The benefit of this way is that we don't need a centralized server the get the right AppKey. Any Developer and run it's MiniApp in its server. The user only needs to load the URI of the MiniApp domain to access the MiniApp.

So, we should build an interoperated MiniApp Platform System. And the MiniApp W3C spec can work for China's business environment.

If we change this way to access MiniApp for the de-centrally remote server. Some sub-questions for fetch the package file is that:

- How to verify the security of a server package resource?

- How to know the specific URI path of the small package resource on the server-side?

- How to obtain remote resources? Do you need to specify the network request protocol? Is HTTP redirect allowed?

- How to ensure that there is no tampering during packet transmission, such as man-in-the-middle attacks?

- Can you protect the security of the incoming packet, such as the problem of tampering?

- Package resource decompression path, should the directories of each source be unified?

- Do you want to prohibit the isolation of small package resource caches of different domain names?

**Comment by zhangyongjing** [comment] 2020-09-11 08:34
My initial thought is to leave the package delivery un-specified, at least for now. So there is not need to standardize the package transmission protocol and secuirty mechanism for that. The main security concern to be addresed is the e2e integrity of the package and the identification of the issuer. This can be solved by signaturing techs e.g. PKCS#7 without specifying the transport layer.

But if the question is whether we should support a brower-based package delivery mechanism, then your proposal seems relevant. Besides, I'd like to clarify the concept of 'AppKey', how is it different from the 'appId' attribute in the current manifest?

**Comment by Ternence** [comment] 2020-09-13 08:46
Yes, this proposal refers to the top-level design of the MiniApp program ecosystem. I hope it can support browser-based package instead of its own centralized services in existing apps. 
This will be very helpful for the ecosystem of openness and interoperability, which will bring the MiniApp program into Web ecosystem.


(My mistake, in fact, the AppKey I said is the AppId. Only in our implementation, we use the pronoun AppKey to express the disorder of AppId.)

**Comment by zhangyongjing** [comment] 2020-09-14 00:59
The problem is still not clear enough to me. Some examples may help, e.g. what is the difference between the current AppId and the AppKey in your mind?

**Comment by Ternence** [comment] 2020-09-14 06:25
In our platform, only the AppKey work for MiniApp Package Fetching.  

- 1. The AppId is MiniApp developer account id.
- 2. The AppKey is the unique id of the real MiniApp package.


![image](https://user-images.githubusercontent.com/2890392/93050635-cdb56a80-f695-11ea-9a10-3e02d60a3429.png)

![image](https://user-images.githubusercontent.com/2890392/93050449-7c0ce000-f695-11ea-90ac-3beee81a6fd5.png)

**Comment by zhangyongjing** [comment] 2020-09-14 06:49
I see. Different vendors/platforms may chose different attribute names in their implementations. In your case, `AppKey` should be mapped to `AppId` in MiniApp, while your `APPID` as you explained as 'developer account id' should be given a better name, e.g. `developerId`. Then it's a question whether the `developerId` needs to appear in the manifest.

**Comment by Ternence** [comment] 2020-09-15 06:14
The developerId is a pure business way. No need design in the manifest spec.

**But in another question I mentioned. How to generate unique appId for every MiniApp? How to keep id unique and vendor can verify appId is the right appId easily?**

1. In URI Spec. We think about using domain-based Id for every MiniApp Package Service. That Service to check whether the AppId is the right id. 
But it, not enough interoperability to the whole ecosystem. It can not check whether an AppId is right from another Package Service.
2. Another way I said. We can use domain only to distinguish every MiniApp id. It likes the H5 domain of the website. Every Vendor and load a MiniApp from its domain. It can load the manifest file firstly. and getting its package archives URI. And then check its digital signature and install it.  

#2 may the next step we need to reach an agreement of vendors.

**Comment by xfq** [comment] 2020-12-11 04:00
Closing per https://www.w3.org/2020/12/10-miniapp-minutes.html#t06

**Closed by xfq** 2020-12-11 04:00 UTC
Labels: packaging
